apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: dhagans
  labels:
    app: app
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  minReadySeconds: 20
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: feature-toggle
        - secretRef:
            name: db-secret
        name: app-deployment
        image: docker pull harbor.dev.afsmtddso.com/dhagans-harbor-project/lab-env-repo@sha256:4d178c15d825d19cb86d3c5cd4d8de2d59ef58f5def50f4cc6ec9700eddcf35c
        ports:
        - containerPort: 5000
